<?php

declare(strict_types=1);

namespace Tests\Unit\Commands;

use App\Support\InstallationAdvisor;
use App\Support\EnvironmentDetector;
use Tests\TestCase;

final class InitDockerCommandTest extends TestCase
{
    private InstallationAdvisor $advisor;

    protected function setUp(): void
    {
        parent::setUp();

        $this->advisor = new InstallationAdvisor(new EnvironmentDetector());
        $this->app->instance(InstallationAdvisor::class, $this->advisor);
    }

    public function testCommandOutputsDockerfileSnippetForXdebug(): void
    {
        $this->artisan('init-docker', ['--debugger' => 'xdebug'])
            ->expectsOutputToContain('Xdebug Configuration')
            ->expectsOutputToContain('pecl install xdebug')
            ->expectsOutputToContain('xdebug.mode=debug')
            ->expectsOutputToContain('xdebug.client_host=host.docker.internal')
            ->expectsOutputToContain('xdebug.start_with_request=yes')
            ->assertSuccessful();
    }

    public function testCommandOutputsDockerfileSnippetForPcov(): void
    {
        $this->artisan('init-docker', ['--debugger' => 'pcov'])
            ->expectsOutputToContain('Pcov Configuration')
            ->expectsOutputToContain('pecl install pcov')
            ->assertSuccessful();
    }

    public function testCommandFailsForUnknownDebugger(): void
    {
        $this->artisan('init-docker', ['--debugger' => 'foobar'])
            ->expectsOutputToContain('Unknown debugger')
            ->assertFailed();
    }

    public function testCommandUsesCustomPort(): void
    {
        $this->artisan('init-docker', ['--debugger' => 'xdebug', '--port' => '9001'])
            ->expectsOutputToContain('xdebug.client_port=9001')
            ->assertSuccessful();
    }

    public function testCommandWritesComposeFile(): void
    {
        $tmpDir = sys_get_temp_dir() . '/debug-pilot-test-' . uniqid();
        mkdir($tmpDir, 0755, true);

        try {
            $this->artisan('init-docker', [
                '--debugger' => 'xdebug',
                '--write-compose' => true,
                '--project-path' => $tmpDir,
            ])->assertSuccessful();

            $composeFile = $tmpDir . '/docker-compose.debug.yml';
            $this->assertFileExists($composeFile);

            $content = file_get_contents($composeFile);
            $this->assertStringContainsString('Generated by PHP Debug Pilot', $content);
            $this->assertStringContainsString('XDEBUG_MODE', $content);
            $this->assertStringContainsString('host.docker.internal', $content);
        } finally {
            // Cleanup
            if (is_file($tmpDir . '/docker-compose.debug.yml')) {
                unlink($tmpDir . '/docker-compose.debug.yml');
            }
            if (is_dir($tmpDir)) {
                rmdir($tmpDir);
            }
        }
    }

    public function testComposeContentForPcov(): void
    {
        $tmpDir = sys_get_temp_dir() . '/debug-pilot-test-' . uniqid();
        mkdir($tmpDir, 0755, true);

        try {
            $this->artisan('init-docker', [
                '--debugger' => 'pcov',
                '--write-compose' => true,
                '--project-path' => $tmpDir,
            ])->assertSuccessful();

            $composeFile = $tmpDir . '/docker-compose.debug.yml';
            $this->assertFileExists($composeFile);

            $content = file_get_contents($composeFile);
            $this->assertStringContainsString('PCOV_ENABLED', $content);
        } finally {
            if (is_file($tmpDir . '/docker-compose.debug.yml')) {
                unlink($tmpDir . '/docker-compose.debug.yml');
            }
            if (is_dir($tmpDir)) {
                rmdir($tmpDir);
            }
        }
    }

    public function testDefaultDebuggerIsXdebug(): void
    {
        $this->artisan('init-docker')
            ->expectsOutputToContain('Xdebug Configuration')
            ->assertSuccessful();
    }
}
