<?php

declare(strict_types=1);

namespace App\Commands;

use App\Support\InstallationAdvisor;
use LaravelZero\Framework\Commands\Command;

/**
 * Generate Docker configuration snippets for PHP debugging.
 *
 * Outputs a ready-to-use Dockerfile snippet and optionally writes
 * a docker-compose override file with debug environment variables.
 *
 * Usage:
 *   debug-pilot init-docker
 *   debug-pilot init-docker --debugger=pcov
 *   debug-pilot init-docker --write-compose
 */
final class InitDockerCommand extends Command
{
    protected $signature = 'init-docker
        {--d|debugger=xdebug : Debugger to configure (xdebug, pcov)}
        {--port=9003 : Debug client port}
        {--write-compose : Write docker-compose.debug.yml to project}
        {--p|project-path= : Project root path}';

    protected $description = 'Generate Docker configuration snippets for PHP debugging';

    private const KNOWN_DEBUGGERS = ['xdebug', 'pcov'];

    public function handle(InstallationAdvisor $advisor): int
    {
        $debugger = strtolower((string) $this->option('debugger'));
        $port = (int) $this->option('port');
        $projectPath = $this->option('project-path') ?: (string) getcwd();

        if (!in_array($debugger, self::KNOWN_DEBUGGERS, true)) {
            $this->error("Unknown debugger '{$debugger}'. Supported: " . implode(', ', self::KNOWN_DEBUGGERS));
            return self::FAILURE;
        }

        $this->newLine();
        $this->info('🐳 PHP Debug Pilot — Docker Configuration');
        $this->info(str_repeat('=', 45));
        $this->newLine();

        // 1. Print Dockerfile snippet
        $this->printDockerfileSnippet($debugger, $port, $advisor);

        // 2. Optionally write docker-compose override
        if ($this->option('write-compose')) {
            $this->writeComposeFile($debugger, $port, $projectPath);
        }

        $this->newLine();
        $this->info('💡 Tip: Debug Pilot auto-detects Docker and resolves');
        $this->line('   host.docker.internal for you when you run:');
        $this->line('   <info>debug-pilot setup --debugger=' . $debugger . '</info>');

        return self::SUCCESS;
    }

    private function printDockerfileSnippet(string $debugger, int $port, InstallationAdvisor $advisor): void
    {
        $this->info('📄 Add this to your Dockerfile:');
        $this->newLine();

        $installCommand = $advisor->getDockerfileCommand($debugger);

        $lines = [
            "# === PHP Debug Pilot — {$this->humanName($debugger)} Configuration ===",
            $installCommand,
        ];

        if ($debugger === 'xdebug') {
            $confPath = '/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini';
            $lines[] = "RUN echo 'xdebug.mode=debug' >> {$confPath} \\";
            $lines[] = "    && echo 'xdebug.client_host=host.docker.internal' >> {$confPath} \\";
            $lines[] = "    && echo 'xdebug.client_port={$port}' >> {$confPath} \\";
            $lines[] = "    && echo 'xdebug.start_with_request=yes' >> {$confPath}";
        }

        foreach ($lines as $line) {
            $this->line("  {$line}");
        }
    }

    private function writeComposeFile(string $debugger, int $port, string $projectPath): void
    {
        $filePath = rtrim($projectPath, '/') . '/docker-compose.debug.yml';

        $content = $this->generateComposeContent($debugger, $port);

        if (file_put_contents($filePath, $content) === false) {
            $this->error("❌ Failed to write {$filePath}");
            return;
        }

        $this->newLine();
        $this->info("✅ Created: {$filePath}");
        $this->newLine();
        $this->line('  Use it with:');
        $this->line('  <info>docker compose -f docker-compose.yml -f docker-compose.debug.yml up</info>');
    }

    /**
     * Generate the docker-compose override YAML content.
     */
    public function generateComposeContent(string $debugger, int $port): string
    {
        $lines = [
            '# Generated by PHP Debug Pilot',
            '# Usage: docker compose -f docker-compose.yml -f docker-compose.debug.yml up',
            '',
            'services:',
            '  app:',
            '    environment:',
        ];

        if ($debugger === 'xdebug') {
            $lines[] = '      XDEBUG_MODE: "debug"';
            $lines[] = "      XDEBUG_CONFIG: \"client_host=host.docker.internal client_port={$port}\"";
        } elseif ($debugger === 'pcov') {
            $lines[] = '      PCOV_ENABLED: "1"';
        }

        $lines[] = '    extra_hosts:';
        $lines[] = '      - "host.docker.internal:host-gateway"';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function humanName(string $debugger): string
    {
        return match ($debugger) {
            'xdebug' => 'Xdebug',
            'pcov' => 'Pcov',
            default => ucfirst($debugger),
        };
    }
}
